import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync } from 'node:fs';

// Ship ONNX Runtime wasm files alongside main.js — bundling can't include
// binary .wasm assets, and relying on CDN fails in restricted networks.
function copyOnnxWasmFiles() {
  const src = 'node_modules/onnxruntime-web/dist';
  const dst = '.';
  mkdirSync(dst, { recursive: true });
  for (const f of ['ort-wasm.wasm', 'ort-wasm-simd.wasm']) {
    copyFileSync(`${src}/${f}`, `${dst}/${f}`);
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === 'production';

const mainConfig = {
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
};

// Worker entry: browser platform, no Node externals (the worker must not depend on Node builtins).
// mainFields:['browser','module','main'] makes mammoth pick its browser entry.
const workerConfig = {
  banner: { js: banner },
  entryPoints: ['src/extraction/worker/extractor.worker.ts'],
  bundle: true,
  external: [],
  platform: 'browser',
  mainFields: ['browser', 'module', 'main'],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'extractor.worker.js',
  minify: prod,
};

// @xenova/transformers uses BigInt (ES2020+), so this worker must target es2020.
// alias onnxruntime-node → onnxruntime-web: in Electron the renderer exposes
// `process.release.name === 'node'`, which makes transformers pick the node
// ONNX runtime — but only onnxruntime-web works in a browser/worker context.
// Forcing both code paths to resolve to the web variant ensures the InferenceSession
// export is real, not undefined.
//
// define: rewrite `process.versions.node` and `process.release.name` at build
// time to literal undefined. onnxruntime-web's emscripten runtime detects Node
// with `typeof process.versions.node === "string"` — true in Electron worker,
// false on the web. We need the false branch so emscripten loads wasm via
// fetch (which our interceptor handles) instead of require('path').dirname.
// Same fix forces @xenova/transformers to pick its web import path.
// We can't patch the real process object — Electron freezes versions.
const embeddingWorkerConfig = {
  banner: { js: banner },
  entryPoints: ['src/embedding/worker/embedding.worker.ts'],
  bundle: true,
  external: [],
  platform: 'browser',
  mainFields: ['browser', 'module', 'main'],
  alias: {
    'onnxruntime-node': 'onnxruntime-web',
  },
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'embedding.worker.js',
  minify: prod,
};

copyOnnxWasmFiles();

if (prod) {
  await Promise.all([
    esbuild.build(mainConfig),
    esbuild.build(workerConfig),
    esbuild.build(embeddingWorkerConfig),
  ]);
  process.exit(0);
} else {
  const mainCtx = await esbuild.context(mainConfig);
  const workerCtx = await esbuild.context(workerConfig);
  const embWorkerCtx = await esbuild.context(embeddingWorkerConfig);
  await Promise.all([mainCtx.watch(), workerCtx.watch(), embWorkerCtx.watch()]);
}
