import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import { copyFileSync, mkdirSync, readFileSync } from 'node:fs';
import { promises as fsp } from 'node:fs';

// Obsidian's automated review flags any `createElement("script")` as a
// CODE OBFUSCATION error ("dynamically injecting script elements can load and
// execute arbitrary external code"). Our only occurrences come from two
// transitive setImmediate polyfills (`immediate`, `setimmediate`, pulled in via
// jszip/lie -> pdfjs-dist/xlsx). Both contain a legacy IE 6–8 fallback that
// creates a <script> element. That path is dead code in Chromium/Electron
// (the `'onreadystatechange' in createElement('script')` feature-detect is
// false; Obsidian uses the MessageChannel/postMessage path). This plugin
// removes that legacy branch at build time so the bundle genuinely never
// creates a script element — this is dead-code removal, not static-analysis
// evasion. It throws if a pattern stops matching (dep upgrade) so a future
// release fails loudly instead of silently shipping the shim again.
const stripLegacyScriptShim = {
  name: 'strip-legacy-setimmediate-script-shim',
  setup(build) {
    build.onLoad(
      { filter: /[\\/]immediate[\\/]lib[\\/]index\.js$/ },
      async (args) => {
        const src = await fsp.readFile(args.path, 'utf8');
        const re =
          /\} else if \('document' in global && 'onreadystatechange' in global\.document\.createElement\('script'\)\) \{[\s\S]*?\n {2}\} else \{/;
        if (!re.test(src)) {
          throw new Error(
            `strip-legacy-setimmediate-script-shim: pattern no longer matches ${args.path} (dependency 'immediate' changed?)`
          );
        }
        return { contents: src.replace(re, '} else {'), loader: 'js' };
      }
    );
    // jszip ships its OWN browserified copies of `immediate` and `setimmediate`
    // inside dist/jszip.min.js (its package.json `browser` field maps the entry
    // here, so esbuild bundles this file, not the standalone deps). Collapse
    // each legacy IE ternary to its real setTimeout fallback branch.
    build.onLoad(
      { filter: /[\\/]jszip[\\/]dist[\\/]jszip\.min\.js$/ },
      async (args) => {
        let src = await fsp.readFile(args.path, 'utf8');
        // immediate-style: VAR="document"in G&&"onreadystatechange"in
        //   G.document.createElement("script")?function(){...}:function(){setTimeout(H,0)};
        const immRe =
          /([\w$]+=)"document"in [\w$]+&&"onreadystatechange"in [\w$]+\.document\.createElement\("script"\)\?function\(\)\{var [\w$]+=[\w$]+\.document\.createElement\("script"\);[\s\S]*?\}:(function\(\)\{setTimeout\([\w$]+,0\)\});/;
        // setimmediate-style: G&&"onreadystatechange"in G.createElement("script")
        //   ?(S=G.documentElement,function(e){...}):function(e){setTimeout(C,0,e)}
        const siRe =
          /[\w$]+&&"onreadystatechange"in [\w$]+\.createElement\("script"\)\?\([\w$]+=[\w$]+\.documentElement,function\([\w$]+\)\{var [\w$]+=[\w$]+\.createElement\("script"\);[\s\S]*?\}\):(function\([\w$]+\)\{setTimeout\([\w$]+,0,[\w$]+\)\})/;
        if (!immRe.test(src) || !siRe.test(src)) {
          throw new Error(
            `strip-legacy-setimmediate-script-shim: pattern no longer matches ${args.path} (dependency 'jszip' changed?)`
          );
        }
        src = src
          .replace(immRe, '$1$2;')
          .replace(siRe, '$1');
        return { contents: src, loader: 'js' };
      }
    );
    build.onLoad(
      { filter: /[\\/]setimmediate[\\/]setImmediate\.js$/ },
      async (args) => {
        let src = await fsp.readFile(args.path, 'utf8');
        const bodyRe =
          /function installReadyStateChangeImplementation\(\) \{[\s\S]*?\n {4}\}/;
        const condRe =
          /\} else if \(doc && "onreadystatechange" in doc\.createElement\("script"\)\) \{/;
        if (!bodyRe.test(src) || !condRe.test(src)) {
          throw new Error(
            `strip-legacy-setimmediate-script-shim: pattern no longer matches ${args.path} (dependency 'setimmediate' changed?)`
          );
        }
        src = src
          .replace(
            bodyRe,
            'function installReadyStateChangeImplementation() {\n        installSetTimeoutImplementation();\n    }'
          )
          .replace(condRe, '} else if (false) {');
        return { contents: src, loader: 'js' };
      }
    );
  },
};

// Ship ONNX Runtime wasm files alongside main.js — bundling can't include
// binary .wasm assets, and relying on CDN fails in restricted networks.
function copyOnnxWasmFiles() {
  const src = 'node_modules/onnxruntime-web/dist';
  const dst = '.';
  mkdirSync(dst, { recursive: true });
  for (const f of ['ort-wasm.wasm', 'ort-wasm-simd.wasm']) {
    copyFileSync(`${src}/${f}`, `${dst}/${f}`);
  }
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === 'production';

const mainConfig = {
  banner: { js: banner },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  minify: prod,
  plugins: [stripLegacyScriptShim],
};

// Worker entry: browser platform, no Node externals (the worker must not depend on Node builtins).
// mainFields:['browser','module','main'] makes mammoth pick its browser entry.
const workerConfig = {
  banner: { js: banner },
  entryPoints: ['src/extraction/worker/extractor.worker.ts'],
  bundle: true,
  external: [],
  platform: 'browser',
  mainFields: ['browser', 'module', 'main'],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'extractor.worker.js',
  minify: prod,
  plugins: [stripLegacyScriptShim],
};

// @xenova/transformers uses BigInt (ES2020+), so this worker must target es2020.
// alias onnxruntime-node → onnxruntime-web: in Electron the renderer exposes
// `process.release.name === 'node'`, which makes transformers pick the node
// ONNX runtime — but only onnxruntime-web works in a browser/worker context.
// Forcing both code paths to resolve to the web variant ensures the InferenceSession
// export is real, not undefined.
//
// define: rewrite `process.versions.node` and `process.release.name` at build
// time to literal undefined. onnxruntime-web's emscripten runtime detects Node
// with `typeof process.versions.node === "string"` — true in Electron worker,
// false on the web. We need the false branch so emscripten loads wasm via
// fetch (which our interceptor handles) instead of require('path').dirname.
// Same fix forces @xenova/transformers to pick its web import path.
// We can't patch the real process object — Electron freezes versions.
const embeddingWorkerConfig = {
  banner: { js: banner },
  entryPoints: ['src/embedding/worker/embedding.worker.ts'],
  bundle: true,
  external: [],
  platform: 'browser',
  mainFields: ['browser', 'module', 'main'],
  alias: {
    'onnxruntime-node': 'onnxruntime-web',
  },
  format: 'cjs',
  target: 'es2020',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'embedding.worker.js',
  minify: prod,
  plugins: [stripLegacyScriptShim],
};

copyOnnxWasmFiles();

if (prod) {
  await Promise.all([
    esbuild.build(mainConfig),
    esbuild.build(workerConfig),
    esbuild.build(embeddingWorkerConfig),
  ]);
  // Guard: Obsidian's review rejects any dynamic <script> creation. Fail the
  // build if the legacy setImmediate shim leaked through (e.g. dep upgraded).
  const scriptRe = /createElement\(\s*["'`]script["'`]\s*\)/;
  for (const f of ['main.js', 'extractor.worker.js', 'embedding.worker.js']) {
    if (scriptRe.test(readFileSync(f, 'utf8'))) {
      console.error(
        `Build guard failed: ${f} still contains a dynamic script-element creation.`
      );
      process.exit(1);
    }
  }
  process.exit(0);
} else {
  const mainCtx = await esbuild.context(mainConfig);
  const workerCtx = await esbuild.context(workerConfig);
  const embWorkerCtx = await esbuild.context(embeddingWorkerConfig);
  await Promise.all([mainCtx.watch(), workerCtx.watch(), embWorkerCtx.watch()]);
}
