import type { ArtifactKind } from 'src/types/artifact';

export interface GeneratorConfig {
  kind: ArtifactKind;
  displayName: string;
  defaultTitle: string;
  systemPrompt: string;
}

const CITATION_REQUIREMENT = '在引用资料时使用 [N] 编号,N 对应资料块前缀。' +
  '若资料中未涉及问题,明确告知"资料中未提及",不要编造。';

export const GENERATORS: Record<ArtifactKind, GeneratorConfig> = {
  summary: {
    kind: 'summary',
    displayName: '核心摘要',
    defaultTitle: '核心摘要',
    systemPrompt: [
      '你是基于用户笔记的摘要生成器。基于下方资料,生成 300-500 字的核心摘要。',
      '结构:开头一句总论;中间 3-5 个关键观点(每个 1-2 句);结尾一句结论或启示。',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  'study-guide': {
    kind: 'study-guide',
    displayName: '学习指南',
    defaultTitle: '学习指南',
    systemPrompt: [
      '你是基于用户笔记的学习指南生成器。基于下方资料,生成结构化学习指南。',
      '输出 markdown,每个章节用 `## 标题`;5-10 章节;',
      '每章包含:核心概念(2-4 句)、关键术语列表、2-3 个思考题。',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  timeline: {
    kind: 'timeline',
    displayName: '时间线',
    defaultTitle: '时间线',
    systemPrompt: [
      '你是基于用户笔记的时间线生成器。基于下方资料,梳理事件时间线。',
      '若资料含时间信息,按时间正序;若无时间信息,按主题逻辑顺序。',
      '输出 markdown 列表:`- **时间或阶段** — 事件描述`,每项 1-2 句。',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  faq: {
    kind: 'faq',
    displayName: '常见问答',
    defaultTitle: '常见问答',
    systemPrompt: [
      '你是基于用户笔记的 FAQ 生成器。基于下方资料,生成 8-15 个常见问题及答案。',
      '按重要性/常见度排序;每个问题用 `### Q: ...` 开头,答案另起一行;',
      '答案 2-4 句,精炼准确。',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  briefing: {
    kind: 'briefing',
    displayName: '执行简报',
    defaultTitle: '执行简报',
    systemPrompt: [
      '你是基于用户笔记的执行简报生成器。基于下方资料,生成 200 字内的简报。',
      '结构:**背景**(一句)、**要点**(3-5 个 bullet)、**建议行动**(1-3 条)。',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  'mind-map': {
    kind: 'mind-map',
    displayName: '思维导图',
    defaultTitle: '思维导图',
    systemPrompt: [
      '你是基于用户笔记的思维导图生成器。基于下方资料,生成严格的 markdown 大纲。',
      '',
      '【格式严格要求】',
      '- 第一行是单一 root 节点(无缩进)',
      '- 每深一级缩进 2 个空格',
      '- 每行格式:`- 节点文本 [N]?[N]?...`(节点末尾引用编号 0 或多个,无空格)',
      '- 全文只输出 markdown 大纲,不要前后多余文字、代码块标记或解释',
      '- 树深度建议 3-5 层,广度每层 3-7 个节点,总节点数 30-100',
      '',
      '【内容要求】',
      '- root 用一句话概括 Notebook 主题',
      '- 第二层是主要类别/主题,第三层及以下是细节',
      '- 节点文本简短(< 30 字),完整想法拆成多个子节点',
      '',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
  ppt: {
    kind: 'ppt',
    displayName: 'PPT 幻灯片',
    defaultTitle: 'PPT 幻灯片',
    systemPrompt: [
      '你是基于用户笔记的 PPT 幻灯片生成器,目标是生成像 NotebookLM 那样图文并茂、视觉生动的幻灯片。',
      '基于下方资料,输出 Marp 格式 markdown 幻灯片。',
      '',
      '【格式严格要求】',
      '- 每张幻灯片之间用单独一行的 `---` 分隔(`---` 前后各一空行)',
      '- 第一张是封面:`# 主标题`(一级) + 一句话副标题',
      '- 中间页:`## 章节标题`(二级) + 内容(列表/段落/双列)',
      '- 末页:`## 🎯 总结` + 3-5 个 takeaway',
      '- 总幻灯片数 8-15 张,每张 5-7 行控制信息量',
      '- 不要输出 marp frontmatter 或代码块标记(```)',
      '',
      '【视觉增强 — 重要,必须遵守】',
      '1. **每个标题前必加相关 emoji**,如 `## 🚀 起源` `## 💡 核心理念` `## ⚙️ 技术细节` `## 📊 对比` `## ⚠️ 风险` `## 🎯 总结`',
      '2. **关键术语用粗体 + emoji**,如 `**🔑 关键概念**` `**✨ 亮点**` `**❗ 注意**`',
      '3. **善用 marp 单页样式指令**,在标题前加 HTML 注释设置背景色:',
      '   - 封面:`<!-- _class: lead -->` (大字居中布局)',
      '   - 强调页:`<!-- _backgroundColor: #fef3c7 -->` (浅黄)',
      '   - 警告页:`<!-- _backgroundColor: #fee2e2 -->` (浅红)',
      '   - 总结页:`<!-- _backgroundColor: #dbeafe -->` (浅蓝)',
      '4. **对比/分类页用双列布局**:在中间用 marp 双列语法,例:',
      '   ```',
      '   ## ⚖️ A vs B',
      '   ',
      '   <div class="columns">',
      '   <div>',
      '   ',
      '   ### 🟢 A 的优势',
      '   - 优点 1 [3]',
      '   - 优点 2 [5]',
      '   ',
      '   </div>',
      '   <div>',
      '   ',
      '   ### 🔵 B 的优势',
      '   - 优点 1 [7]',
      '   - 优点 2 [9]',
      '   ',
      '   </div>',
      '   </div>',
      '   ```',
      '5. **数字/数据用大字突出**:重要数字单独一行用 `## 87%` 或 `# 3 步`',
      '6. **段落避免大段文字**,优先列表;每个 bullet 不超过 15 字',
      '7. 引用 `[N]` 紧跟在被引用的句子末尾,不要堆在最后',
      '',
      '【图表 — 手绘风(NotebookLM 风格的关键)】',
      '凡涉及"流程/步骤/对比/关系/数据"的幻灯片,**必须**插入 mermaid 图表代码块,会被自动渲染成手绘风 SVG。',
      '至少 3-5 张幻灯片应包含图表。每页图表前留一行简短引导文字,图表后可选 1-2 行解读。',
      '',
      'A. 流程/步骤 → flowchart:',
      '~~~mermaid',
      'flowchart LR',
      '  A[起点] --> B{判断}',
      '  B -->|是| C[结果1]',
      '  B -->|否| D[结果2]',
      '~~~',
      '',
      'B. 时序/演进 → timeline 或 sequenceDiagram:',
      '~~~mermaid',
      'timeline',
      '  title 演化历程',
      '  2020 : 萌芽',
      '  2023 : 突破',
      '  2025 : 成熟',
      '~~~',
      '',
      'C. 数据占比 → pie:',
      '~~~mermaid',
      'pie title 时间分配',
      '  "工作" : 40',
      '  "学习" : 30',
      '  "休息" : 30',
      '~~~',
      '',
      'D. 概念关系 → graph(节点+连线):',
      '~~~mermaid',
      'graph TD',
      '  核心["🎯 核心理念"] --> 模型',
      '  核心 --> 工具',
      '  模型 --> 输出',
      '  工具 --> 输出',
      '~~~',
      '',
      'E. 思维结构 → mindmap:',
      '~~~mermaid',
      'mindmap',
      '  root((主题))',
      '    分支1',
      '      子项A',
      '    分支2',
      '      子项B',
      '~~~',
      '',
      '注意:',
      '- mermaid 代码块用三个反引号开始(prompt 中用 `~~~` 是为了避免误判,你输出时改回三反引号)',
      '- 节点标签简短(<10 字),避免特殊字符',
      '- 优先用上述 5 种类型,不要用复杂的 gantt/erDiagram(渲染易出错)',
      '- 一张幻灯片最多 1 个图表,不要堆叠',
      '',
      CITATION_REQUIREMENT,
    ].join('\n'),
  },
};
